'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property WindSpeedOffSwitch() As Double
            Get
                Return CType(Me("WindSpeedOffSwitch"),Double)
            End Get
            Set
                Me("WindSpeedOffSwitch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0600")>  _
        Public Property TimerOnTime() As String
            Get
                Return CType(Me("TimerOnTime"),String)
            End Get
            Set
                Me("TimerOnTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property TimerOffTime() As String
            Get
                Return CType(Me("TimerOffTime"),String)
            End Get
            Set
                Me("TimerOffTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public ReadOnly Property ForeCastDays() As Integer
            Get
                Return CType(Me("ForeCastDays"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WriteHTMLFile() As Boolean
            Get
                Return CType(Me("WriteHTMLFile"),Boolean)
            End Get
            Set
                Me("WriteHTMLFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\DLRStuff\MySwitchData\")>  _
        Public Property HTMLOutFileLocation() As String
            Get
                Return CType(Me("HTMLOutFileLocation"),String)
            End Get
            Set
                Me("HTMLOutFileLocation") = value
            End Set
        End Property
        
      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("KOROTIS10")> _
      Public Property StationIDMain() As String
         Get
            Return CType(Me("StationIDMain"), String)
         End Get
         Set(value As String)
            Me("StationIDMain") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("False")> _
      Public Property WriteStatistcalFile() As Boolean
         Get
            Return CType(Me("WriteStatistcalFile"), Boolean)
         End Get
         Set(value As Boolean)
            Me("WriteStatistcalFile") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("C:\DLRStuff\MySwitchData\")> _
      Public Property StatisticalFileLocation() As String
         Get
            Return CType(Me("StatisticalFileLocation"), String)
         End Get
         Set(value As String)
            Me("StatisticalFileLocation") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("C:\DLRStuff\MySwitchData\")> _
      Public Property SwitchLogLocation() As String
         Get
            Return CType(Me("SwitchLogLocation"), String)
         End Get
         Set(value As String)
            Me("SwitchLogLocation") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("60000")> _
      Public Property SleepTimer() As Integer
         Get
            Return CType(Me("SleepTimer"), Integer)
         End Get
         Set(value As Integer)
            Me("SleepTimer") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("10")> _
      Public Property MondayOn1() As Integer
         Get
            Return CType(Me("MondayOn1"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOn1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("100")> _
      Public Property MondayOn2() As Integer
         Get
            Return CType(Me("MondayOn2"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOn2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("250")> _
      Public Property MondayOn3() As Integer
         Get
            Return CType(Me("MondayOn3"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOn3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("1000")> _
      Public Property MondayOn4() As Integer
         Get
            Return CType(Me("MondayOn4"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOn4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property MondayOff1() As Integer
         Get
            Return CType(Me("MondayOff1"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOff1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property MondayOff2() As Integer
         Get
            Return CType(Me("MondayOff2"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOff2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property MondayOff3() As Integer
         Get
            Return CType(Me("MondayOff3"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOff3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property MondayOff4() As Integer
         Get
            Return CType(Me("MondayOff4"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOff4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOn1() As Integer
         Get
            Return CType(Me("TuesdayOn1"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOn1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOn2() As Integer
         Get
            Return CType(Me("TuesdayOn2"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOn2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOn3() As Integer
         Get
            Return CType(Me("TuesdayOn3"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOn3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOn4() As Integer
         Get
            Return CType(Me("TuesdayOn4"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOn4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOff1() As Integer
         Get
            Return CType(Me("TuesdayOff1"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOff1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOff2() As Integer
         Get
            Return CType(Me("TuesdayOff2"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOff2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOff3() As Integer
         Get
            Return CType(Me("TuesdayOff3"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOff3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOff4() As Integer
         Get
            Return CType(Me("TuesdayOff4"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOff4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOn1() As Integer
         Get
            Return CType(Me("WednesdayOn1"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOn1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOn2() As Integer
         Get
            Return CType(Me("WednesdayOn2"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOn2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOn3() As Integer
         Get
            Return CType(Me("WednesdayOn3"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOn3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOn4() As Integer
         Get
            Return CType(Me("WednesdayOn4"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOn4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOff1() As Integer
         Get
            Return CType(Me("WednesdayOff1"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOff1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOff2() As Integer
         Get
            Return CType(Me("WednesdayOff2"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOff2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOff3() As Integer
         Get
            Return CType(Me("WednesdayOff3"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOff3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOff4() As Integer
         Get
            Return CType(Me("WednesdayOff4"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOff4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOn1() As Integer
         Get
            Return CType(Me("ThursdayOn1"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOn1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOn2() As Integer
         Get
            Return CType(Me("ThursdayOn2"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOn2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOn3() As Integer
         Get
            Return CType(Me("ThursdayOn3"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOn3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOn4() As Integer
         Get
            Return CType(Me("ThursdayOn4"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOn4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOff1() As Integer
         Get
            Return CType(Me("ThursdayOff1"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOff1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOff2() As Integer
         Get
            Return CType(Me("ThursdayOff2"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOff2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOff3() As Integer
         Get
            Return CType(Me("ThursdayOff3"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOff3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOff4() As Integer
         Get
            Return CType(Me("ThursdayOff4"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOff4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOn1() As Integer
         Get
            Return CType(Me("FridayOn1"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOn1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOn2() As Integer
         Get
            Return CType(Me("FridayOn2"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOn2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOn3() As Integer
         Get
            Return CType(Me("FridayOn3"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOn3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOn4() As Integer
         Get
            Return CType(Me("FridayOn4"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOn4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOff1() As Integer
         Get
            Return CType(Me("FridayOff1"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOff1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOff2() As Integer
         Get
            Return CType(Me("FridayOff2"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOff2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOff3() As Integer
         Get
            Return CType(Me("FridayOff3"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOff3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOff4() As Integer
         Get
            Return CType(Me("FridayOff4"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOff4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOn1() As Integer
         Get
            Return CType(Me("SaturdayOn1"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOn1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOn2() As Integer
         Get
            Return CType(Me("SaturdayOn2"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOn2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOn3() As Integer
         Get
            Return CType(Me("SaturdayOn3"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOn3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOn4() As Integer
         Get
            Return CType(Me("SaturdayOn4"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOn4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOff1() As Integer
         Get
            Return CType(Me("SaturdayOff1"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOff1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOff2() As Integer
         Get
            Return CType(Me("SaturdayOff2"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOff2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOff3() As Integer
         Get
            Return CType(Me("SaturdayOff3"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOff3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOff4() As Integer
         Get
            Return CType(Me("SaturdayOff4"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOff4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOn1() As Integer
         Get
            Return CType(Me("SundayOn1"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOn1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOn2() As Integer
         Get
            Return CType(Me("SundayOn2"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOn2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOn3() As Integer
         Get
            Return CType(Me("SundayOn3"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOn3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOn4() As Integer
         Get
            Return CType(Me("SundayOn4"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOn4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOff1() As Integer
         Get
            Return CType(Me("SundayOff1"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOff1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOff2() As Integer
         Get
            Return CType(Me("SundayOff2"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOff2") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOff3() As Integer
         Get
            Return CType(Me("SundayOff3"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOff3") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOff4() As Integer
         Get
            Return CType(Me("SundayOff4"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOff4") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("1250")> _
      Public Property MondayOn5() As Integer
         Get
            Return CType(Me("MondayOn5"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOn5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property MondayOff5() As Integer
         Get
            Return CType(Me("MondayOff5"), Integer)
         End Get
         Set(value As Integer)
            Me("MondayOff5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOn5() As Integer
         Get
            Return CType(Me("TuesdayOn5"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOn5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property TuesdayOff5() As Integer
         Get
            Return CType(Me("TuesdayOff5"), Integer)
         End Get
         Set(value As Integer)
            Me("TuesdayOff5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOn5() As Integer
         Get
            Return CType(Me("WednesdayOn5"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOn5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property WednesdayOff5() As Integer
         Get
            Return CType(Me("WednesdayOff5"), Integer)
         End Get
         Set(value As Integer)
            Me("WednesdayOff5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOn5() As Integer
         Get
            Return CType(Me("ThursdayOn5"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOn5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property ThursdayOff5() As Integer
         Get
            Return CType(Me("ThursdayOff5"), Integer)
         End Get
         Set(value As Integer)
            Me("ThursdayOff5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOn5() As Integer
         Get
            Return CType(Me("FridayOn5"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOn5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property FridayOff5() As Integer
         Get
            Return CType(Me("FridayOff5"), Integer)
         End Get
         Set(value As Integer)
            Me("FridayOff5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOn5() As Long
         Get
            Return CType(Me("SaturdayOn5"), Long)
         End Get
         Set(value As Long)
            Me("SaturdayOn5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SaturdayOff5() As Integer
         Get
            Return CType(Me("SaturdayOff5"), Integer)
         End Get
         Set(value As Integer)
            Me("SaturdayOff5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOn5() As Integer
         Get
            Return CType(Me("SundayOn5"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOn5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("0")> _
      Public Property SundayOff5() As Integer
         Get
            Return CType(Me("SundayOff5"), Integer)
         End Get
         Set(value As Integer)
            Me("SundayOff5") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("C:\AcuriteData\AcuRite Weather Station\acuriteweather.CSV")> _
      Public Property AccuriteDataFile() As String
         Get
            Return CType(Me("AccuriteDataFile"), String)
         End Get
         Set(value As String)
            Me("AccuriteDataFile") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=")> _
      Public Property StationURLMain() As String
         Get
            Return CType(Me("StationURLMain"), String)
         End Get
         Set(value As String)
            Me("StationURLMain") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("KOROTIS8")> _
      Public Property StationID1() As String
         Get
            Return CType(Me("StationID1"), String)
         End Get
         Set(value As String)
            Me("StationID1") = value
         End Set
      End Property

      <Global.System.Configuration.UserScopedSettingAttribute(), _
       Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
       Global.System.Configuration.DefaultSettingValueAttribute("http://www.wunderground.com/personal-weather-station/dashboard?ID=KIDJEROM2")> _
      Public Property StationJerome1() As String
         Get
            Return CType(Me("StationJerome1"), String)
         End Get
         Set(value As String)
            Me("StationJerome1") = value
         End Set
      End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MyWeatherSwitch.My.MySettings
            Get
                Return Global.MyWeatherSwitch.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
